name: Verify code generation integrity

on: pull_request

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.16.5
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run code generation
        run: make generate

      - name: Test diff
        run: |
          git diff | cat
          git status --porcelain=v1
          test $(git status --porcelain=v1 | wc -l) -eq 0
